// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Calendar struct {
	ID     int32  `json:"id"`
	UserID int32  `json:"user_id"`
	Name   string `json:"name"`
	Key    string `json:"key"`
}

type Favourite struct {
	ID        int32       `json:"id"`
	UserID    int32       `json:"user_id"`
	EventGuid pgtype.UUID `json:"event_guid"`
	EventID   pgtype.Int4 `json:"event_id"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
}
